FROM apache/spark-py:v3.4.0

COPY src/main/resources/launch_ipykernel.py /opt/spark/work-dir/launch_ipykernel.py
COPY src/main/resources/launch_ipykernel_old.py /opt/spark/work-dir/launch_ipykernel_old.py
COPY src/main/resources/launch_ipykernel_eg322.py /opt/spark/work-dir/launch_ipykernel_eg322.py
COPY src/main/resources/launch_toree.jar /opt/spark/work-dir/launch_toree.jar

USER root
RUN chown -R 185:root /opt/spark/work-dir/launch_ipykernel.py
RUN chown -R 185:root /opt/spark/work-dir/launch_ipykernel_old.py
RUN chown -R 185:root /opt/spark/work-dir/launch_ipykernel_eg322.py
RUN chown -R 185:root /opt/spark/work-dir/launch_toree.jar

USER 185