{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmission",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 53302,
          "sha512": "6074691b9b24d48141096c5a4b9825e08ebf511c418df6526082ff50d01a26603ca3290ea5bea6b96e719fc9b544b44d39c9c025e1be32104f0f2430263757f0",
          "sha256": "dd609e33ade01137e4ebe3d88f76a9bfd70fc1dc6dfb031435d7430446a06c47",
          "sha1": "2b30d70c5b127ba9e97e39af9d78b9c9c1aa538d",
          "md5": "5b20a99b141512ddc9cf6fcb01768a18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive-thriftserver_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.23.0"
          }
        },
        {
          "group": "io.kubernetes",
          "module": "client-java",
          "version": {
            "requires": "18.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 53302,
          "sha512": "6074691b9b24d48141096c5a4b9825e08ebf511c418df6526082ff50d01a26603ca3290ea5bea6b96e719fc9b544b44d39c9c025e1be32104f0f2430263757f0",
          "sha256": "dd609e33ade01137e4ebe3d88f76a9bfd70fc1dc6dfb031435d7430446a06c47",
          "sha1": "2b30d70c5b127ba9e97e39af9d78b9c9c1aa538d",
          "md5": "5b20a99b141512ddc9cf6fcb01768a18"
        }
      ]
    }
  ]
}
