{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmission",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 51915,
          "sha512": "d0c15ade5d181ddce467c44c500877cb4c1b75de31b4c59f9af71c6c1c48e5287a981a17af136de751181a94cd6c778dc88d36caa9bd00559e9024ea9f56cde4",
          "sha256": "12b4ee7cc59bfea5ed8f335accb3c6c82f68d3c5bb344129e6614066522ba348",
          "sha1": "70f506aa8813368d8c0876977da917d6dbfda411",
          "md5": "1d2c231dff406ebfd255247a02b166aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive-thriftserver_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.23.0"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 51915,
          "sha512": "d0c15ade5d181ddce467c44c500877cb4c1b75de31b4c59f9af71c6c1c48e5287a981a17af136de751181a94cd6c778dc88d36caa9bd00559e9024ea9f56cde4",
          "sha256": "12b4ee7cc59bfea5ed8f335accb3c6c82f68d3c5bb344129e6614066522ba348",
          "sha1": "70f506aa8813368d8c0876977da917d6dbfda411",
          "md5": "1d2c231dff406ebfd255247a02b166aa"
        }
      ]
    }
  ]
}
