{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmission",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 50857,
          "sha512": "fb7a113ae7db5bea5c3648526ba12fa739293ae4ca0004c8a011eab677e3481825e79a1f73afa63bc234f8d67035a5e215c2dde13f6c42a7a4b0fb2b20ccd295",
          "sha256": "c0074986610a140b7680b5626671e279258675b27393746f751bbb1676af7611",
          "sha1": "e0f0a27730af03ac49f20c76564357ecbedff7f8",
          "md5": "b524bf0a95cede3a9d3aaba7cbe47ebf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive-thriftserver_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.23.0"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 50857,
          "sha512": "fb7a113ae7db5bea5c3648526ba12fa739293ae4ca0004c8a011eab677e3481825e79a1f73afa63bc234f8d67035a5e215c2dde13f6c42a7a4b0fb2b20ccd295",
          "sha256": "c0074986610a140b7680b5626671e279258675b27393746f751bbb1676af7611",
          "sha1": "e0f0a27730af03ac49f20c76564357ecbedff7f8",
          "md5": "b524bf0a95cede3a9d3aaba7cbe47ebf"
        }
      ]
    }
  ]
}
