{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmit",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmit-1.0.jar",
          "url": "codesubmit-1.0.jar",
          "size": 8757,
          "sha512": "b202e0d2e214aa0ac0f4724f9de244401f43d609f473908e96b6696e93667da8aee8e6abae1eb34cc83a41c77cc04adada7c20ec8b583aca2fc6c7205d7cbf37",
          "sha256": "b5dbefb3f86bd917a96bc330fe5cfd0f971f91dd23c33332452c09199cc4a645",
          "sha1": "9a9b1ca1b0b4524dc19612dbdcd20fb90a08310e",
          "md5": "3a95d8208615dab0b364b07962deaa20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.4.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmit-1.0.jar",
          "url": "codesubmit-1.0.jar",
          "size": 8757,
          "sha512": "b202e0d2e214aa0ac0f4724f9de244401f43d609f473908e96b6696e93667da8aee8e6abae1eb34cc83a41c77cc04adada7c20ec8b583aca2fc6c7205d7cbf37",
          "sha256": "b5dbefb3f86bd917a96bc330fe5cfd0f971f91dd23c33332452c09199cc4a645",
          "sha1": "9a9b1ca1b0b4524dc19612dbdcd20fb90a08310e",
          "md5": "3a95d8208615dab0b364b07962deaa20"
        }
      ]
    }
  ]
}
