{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 9561,
          "sha512": "939eb420b319319e53156dda410f748fa0996c754db93af5ad5416ef183a572045fb1f280d7963fdc8c30cbccae25357e1cfbd54d90e28d0920fc5a81ed75642",
          "sha256": "20b934aa673528a81e9bdd6f3541cc9fdb09f9a7240759c822a1b6733655101f",
          "sha1": "e8b48c35cbb930960b00d70030b16ac571a5721e",
          "md5": "8832bdfbba9acccd18798634ee845f9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.4.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 9561,
          "sha512": "939eb420b319319e53156dda410f748fa0996c754db93af5ad5416ef183a572045fb1f280d7963fdc8c30cbccae25357e1cfbd54d90e28d0920fc5a81ed75642",
          "sha256": "20b934aa673528a81e9bdd6f3541cc9fdb09f9a7240759c822a1b6733655101f",
          "sha1": "e8b48c35cbb930960b00d70030b16ac571a5721e",
          "md5": "8832bdfbba9acccd18798634ee845f9d"
        }
      ]
    }
  ]
}
