{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 9497,
          "sha512": "249201862f70b7f01ce13d32784d42d809867a1b4274343e67c9b26e5dc1fafa1da442e907a4423c03fc08c4aa77181b406e5b30350a265c7ac76ec6c392f258",
          "sha256": "f10ff89e456534bdd3c6d5305fa171e5cbe2be83f90e03b98bd86c6cad4da518",
          "sha1": "59a7c0dd9aea1477aa256138b11ce99835b9cf6b",
          "md5": "25b8b1e67f9673db218432a0a85c0396"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.4.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 9497,
          "sha512": "249201862f70b7f01ce13d32784d42d809867a1b4274343e67c9b26e5dc1fafa1da442e907a4423c03fc08c4aa77181b406e5b30350a265c7ac76ec6c392f258",
          "sha256": "f10ff89e456534bdd3c6d5305fa171e5cbe2be83f90e03b98bd86c6cad4da518",
          "sha1": "59a7c0dd9aea1477aa256138b11ce99835b9cf6b",
          "md5": "25b8b1e67f9673db218432a0a85c0396"
        }
      ]
    }
  ]
}
