{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 14735,
          "sha512": "171220c238560d70a102d5fde7fdfa4df7254494a9c86b49a1cd5ad873e3b7b57022b4299e7e29b72b6a950677f09d6aae43fb81d1e4c644d27a166aef0abc6d",
          "sha256": "0e5f3cff7d5e38f67266d0b1542ead19cadd76d9772f0e4a649868f72273ff7d",
          "sha1": "79e3406df68d1dd364de1d6592935151c0659272",
          "md5": "ec39196cb45c13affd3a64e17c37f4c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 14735,
          "sha512": "171220c238560d70a102d5fde7fdfa4df7254494a9c86b49a1cd5ad873e3b7b57022b4299e7e29b72b6a950677f09d6aae43fb81d1e4c644d27a166aef0abc6d",
          "sha256": "0e5f3cff7d5e38f67266d0b1542ead19cadd76d9772f0e4a649868f72273ff7d",
          "sha1": "79e3406df68d1dd364de1d6592935151c0659272",
          "md5": "ec39196cb45c13affd3a64e17c37f4c3"
        }
      ]
    }
  ]
}
